import { Event } from '../types';

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: 'React Native Workshop',
    date: 'Oct 26, 2024',
    time: '7:00 PM',
    shortDescription: 'A deep dive into advanced React Native concepts, state management, and performance optimization.',
    fullDescription: 'Join us for an intensive workshop covering advanced React Native topics including performance optimization, custom native modules, and best practices for large-scale applications. Perfect for developers looking to level up their skills.',
    location: 'Tech Hub, Lagos',
  },
  {
    id: '2',
    title: 'Design Systems in Figma',
    date: 'Nov 1, 2024',
    time: '10:00 AM',
    shortDescription: 'Learn how to create and maintain a design system for scalability and consistency across your products.',
    fullDescription: 'Discover the secrets to building robust design systems in Figma. We\'ll cover component libraries, design tokens, documentation, and collaboration workflows that ensure consistency across your product ecosystem.',
    location: 'Design Studio, Victoria Island',
  },
  {
    id: '3',
    title: 'Introduction to SwiftUI',
    date: 'Nov 5, 2024',
    time: '2:00 PM',
    shortDescription: 'A beginner-friendly workshop on Apple\'s latest UI framework for building beautiful native apps.',
    fullDescription: 'Start your SwiftUI journey with this comprehensive introduction. Learn the fundamentals of declarative UI, state management, and building responsive interfaces for iOS, macOS, and more.',
    location: 'Apple Developer Center, Ikoyi',
  },
  {
    id: '4',
    title: 'TypeScript Masterclass',
    date: 'Nov 12, 2024',
    time: '5:00 PM',
    shortDescription: 'Master advanced TypeScript patterns and techniques for building type-safe applications.',
    fullDescription: 'Take your TypeScript skills to the next level with advanced generics, utility types, conditional types, and architectural patterns. Learn how to leverage TypeScript\'s powerful type system for robust applications.',
    location: 'Code Academy, Lekki',
  },
  {
    id: '5',
    title: 'Summer Music Festival',
    date: 'Aug 10, 2025',
    time: '2:00 PM',
    shortDescription: 'Experience an unforgettable day of live music performances in Central Park.',
    fullDescription: 'The annual Summer Music Festival returns with an incredible lineup of local and international artists. Enjoy food trucks, art installations, and amazing performances across multiple stages in the heart of Central Park.',
    location: 'Central Park, New York',
  },
  {
    id: '6',
    title: 'Innovate Tech Conference',
    date: 'Mon, Oct 28, 2025',
    time: '9:00 AM',
    shortDescription: 'A premier technology conference featuring industry leaders and innovators.',
    fullDescription: 'Join thousands of tech professionals for three days of keynotes, workshops, and networking. Explore the latest in AI, blockchain, cloud computing, and emerging technologies shaping our future.',
    location: 'Moscone Center, San Francisco',
  },
  {
    id: '7',
    title: 'Coachella Music Festival',
    date: 'Apr 12, 2025',
    time: '3:00 PM',
    shortDescription: 'An iconic music and arts festival featuring top international artists.',
    fullDescription: 'Join thousands of music lovers at Coachella in California for unforgettable performances, art installations, and a vibrant festival experience across multiple stages.',
    location: 'Indio, California, USA',
  },
  {
    id: '8',
    title: 'Wimbledon Finals',
    date: 'Jul 12, 2025',
    time: '2:00 PM',
    shortDescription: 'The grand finale of the world-famous tennis championship.',
    fullDescription: 'Watch the world\'s top tennis players battle for the prestigious Wimbledon title in London. Experience thrilling matches on grass courts with a global audience.',
    location: 'London, UK',
  },
  {
    id: '9',
    title: 'Rio Carnival Parade',
    date: 'Feb 22, 2025',
    time: '6:00 PM',
    shortDescription: 'A spectacular celebration of music, dance, and culture.',
    fullDescription: 'Experience the vibrant Rio Carnival with samba parades, colorful costumes, and street parties. One of the most famous cultural events in the world.',
    location: 'Rio de Janeiro, Brazil',
  },
  {
    id: '10',
    title: 'NBA All-Star Game',
    date: 'Feb 16, 2025',
    time: '7:00 PM',
    shortDescription: 'A showcase of the NBA\'s best basketball talent from around the globe.',
    fullDescription: 'Watch the top NBA players compete in an exciting exhibition game featuring slam dunk contests, 3-point shootouts, and unforgettable basketball action.',
    location: 'Paris, France',
  },
  {
    id: '11',
    title: 'Edinburgh Fringe Festival',
    date: 'Aug 05, 2025',
    time: '12:00 PM',
    shortDescription: 'The world\'s largest arts festival, featuring theater, comedy, and music.',
    fullDescription: 'Explore thousands of performances across Edinburgh, from comedy and theater to music and experimental art. A must-visit for arts enthusiasts.',
    location: 'Edinburgh, Scotland',
  },
  {
    id: '12',
    title: 'Tokyo Anime Expo',
    date: 'Jul 18, 2025',
    time: '11:00 AM',
    shortDescription: 'A premier celebration of anime, manga, and Japanese pop culture.',
    fullDescription: 'Join anime fans from around the world at Tokyo Anime Expo. Enjoy panels, screenings, cosplay contests, and exclusive merchandise from top creators.',
    location: 'Tokyo, Japan',
  },
  {
    id: '13',
    title: 'Formula 1 Singapore Grand Prix',
    date: 'Sep 21, 2025',
    time: '5:00 PM',
    shortDescription: 'An exhilarating night race featuring the world\'s fastest drivers.',
    fullDescription: 'Witness the excitement of F1 racing under the dazzling lights of Singapore. Experience high-speed thrills, precision driving, and spectacular entertainment.',
    location: 'Singapore',
  },
  {
    id: '14',
    title: 'Glastonbury Music Festival',
    date: 'Jun 28, 2025',
    time: '1:00 PM',
    shortDescription: 'One of the largest and most famous music festivals in the world.',
    fullDescription: 'Join thousands of fans at Glastonbury in the UK for multiple stages of live music, arts, and performances. A legendary festival experience.',
    location: 'Somerset, UK',
  },
  {
    id: '15',
    title: 'Super Bowl LVIII',
    date: 'Feb 02, 2025',
    time: '8:30 PM',
    shortDescription: 'The biggest annual American football event with global viewership.',
    fullDescription: 'Experience the excitement of the Super Bowl, featuring top NFL teams, halftime shows, and a celebration of sports culture and entertainment.',
    location: 'Las Vegas, Nevada, USA',
  },
  {
    id: '16',
    title: 'Oktoberfest Parade',
    date: 'Sep 20, 2025',
    time: '10:00 AM',
    shortDescription: 'A grand celebration of beer, music, and Bavarian culture.',
    fullDescription: 'Join the iconic Oktoberfest in Munich for parades, traditional beer tents, folk music, and cultural festivities that attract visitors worldwide.',
    location: 'Munich, Germany',
  },
];
